name = "mkp-tri"
main = "workers/router.ts"
compatibility_date = "2024-12-01"

routes = [
	{ pattern = "mkptri.org/*", zone_name = "mkptri.org" }
]

[vars]
OMNI_ENDPOINT = "https://example-omni-endpoint"
CODEX_BUCKET = "mkp-codex"

[site]
bucket = "./dist"
